### ISSUE TITLE
Fixquestiontime error

### ISSUE THREAD

**Issue by Undeadking176** [Nocturne123/QuestionsTime#9]
im having this issue for some reason is there something wrong with the java file!
[05:23:37] [pool-2-thread-13/ERROR] [Sponge]: The Scheduler tried to run the task [QT]FixTimeQuestion owned by Plugin{id=questionstime, name=QuestionsTime, version=1.1.7, description=Ask questions and gain prize for the winner, authors=[Nocturne123], source=./mods/QuestionsTime-1.1.7.jar}, but an error occured.
java.lang.IllegalArgumentException: bound must be positiveat java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_352]at fr.nocturne123.questionstime.QuestionTask.run(QuestionTask.java:43) ~[QuestionTask.class:?]at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.4.8-RC4141]at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.4.8-RC4141]at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_352]at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_352]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]

**Comment by AlexandreArcil** [comment]
Hello,
Can you give the content of `config.conf` ? I think that the sum of the weight of the questions is <= 0.

**Comment by Undeadking176** [comment]
``# Reminder : 1 tick = 0.05 second, 1 second = 20 ticks, 1 minute = 1200 ticks, 1 hour = 72 000 ticks
# "timer" and "time-between-answer" are to be in seconds

# The time in ticks between each questions
cooldown=3000
# The max cooldown in tick a question can be said
maxCooldown=72000
# The minimum of players connected to ask a question.
minConnected=2
# The min cooldown in tick before a question can be said
minCooldown=36000
# If true, the answer given by player stay personnal and is not send to the global chat. If false, every answer is send to the global chat
personalAnswer=false
questions {
    Howmanytinypotatoesarehiddeninspawn {
        answer="2"
        malus {
            announce=false
            money=0
        }
        prize {
            announce=true
            money=200
        }
        proposition=[
            "10",
            "15",
            "20",
            "25"
        ]
        question="How many tiny potatoes are hidden in spawn?"
        time-between-answer=0
        timer=30
        weight=0
    }
    Howmanytypesofzombiesareinthispack {
        answer="4"
        malus {
            announce=false
            money=0
        }
        prize {
            announce=true
            money=150
        }
        proposition=[
            "2",
            "3",
            "5",
            "6"
        ]
        question="How many types of zombies are in this pack?"
        time-between-answer=0
        timer=30
        weight=0
    }
    WhatareCreepersafraidof {
        answer=Cats
        malus {
            announce=false
            money=0
        }
        prize {
            announce=true
            money=150
        }
        question="What are Creepers afraid of?"
        time-between-answer=0
        timer=30
        weight=0
    }
    Whatdoesavillagerbecomeifstruckbylightning {
        answer=Witch
        malus {
            announce=false
            money=0
        }
        prize {
            announce=true
            money=150
        }
        question="What does a villager become if struck by lightning?"
        time-between-answer=10
        timer=30
        weight=0
    }
    WhatenemymobwasthefirstaddedtoMinecraft {
        answer=Zombie
        malus {
            announce=false
            money=0
        }
        prize {
            announce=true
            money=150
        }
        question="What enemy mob was the first added to Minecraft?"
        time-between-answer=10
        timer=30
        weight=0
    }
    WhatgameheavilyinspiredMinecraft {
        answer=Infiniminer
        malus {
            announce=false
            money=0
        }
        prize {
            announce=true
            money=150
        }
        question="What game heavily inspired Minecraft?"
        time-between-answer=10
        timer=30
        weight=0
    }
    Whatisthenameforavillagerwhocannottrade {
        answer=Nitwit
        malus {
            announce=false
            money=0
        }
        prize {
            announce=true
            money=150
        }
        question="What is the name for a villager who cannot trade?"
        time-between-answer=10
        timer=30
        weight=0
    }
    WhatisthenameofthedefaultfemaleMinecraftskin {
        answer=Alex
        malus {
            announce=false
            money=0
        }
        prize {
            announce=true
            money=150
        }
        question="What is the name of the default female Minecraft skin?"
        time-between-answer=0
        timer=30
        weight=0
    }
    Whatmobwascreatedduetoacodingerrorwithapig {
        answer=Creeper
        malus {
            announce=false
            money=0
        }
        prize {
            announce=true
            money=150
        }
        question="What mob was created due to a coding error with a pig?"
        time-between-answer=10
        timer=30
        weight=0
    }
    WhatwasMinecraftoriginallygoingtobecalled {
        answer="Cave Game"
        malus {
            announce=false
            money=0
        }
        prize {
            announce=true
            money=150
        }
        question="What was Minecraft originally going to be called?"
        time-between-answer=10
        timer=30
        weight=0
    }
    WhatyearwasMinecraftfirstreleased {
        answer="2011"
        malus {
            announce=false
            money=0
        }
        prize {
            announce=true
            money=150
        }
        question="What year was Minecraft first released?"
        time-between-answer=0
        timer=30
        weight=0
    }
    Whichmobcannotswim {
        answer=Enderman
        malus {
            announce=false
            money=0
        }
        prize {
            announce=true
            money=150
        }
        question="Which mob can not swim?"
        time-between-answer=0
        timer=10
        weight=0
    }
    WhowasthefirstPlayertojoinLacunaserver {
        answer=nkedtrucker94
        malus {
            announce=false
            money=0
        }
        prize {
            announce=true
            money=500
        }
        question="Who was the first Player to join Lacuna server?"
        time-between-answer=10
        timer=30
        weight=0
    }
    howmanymetersdoesoneMinecraftblockequal {
        answer="One meter"
        malus {
            announce=false
            money=0
        }
        prize {
            announce=true
            money=150
        }
        question="how many meters does one Minecraft block equal?"
        time-between-answer=0
        timer=60
        weight=0
    }
}
# If true, he will say a new question between minCooldown and maxCooldown, if false, he will say a new question after the cooldown

**Comment by Undeadking176** [comment]
[new 5.txt](https://github.com/AlexandreArcil/QuestionsTime/files/10722853/new.5.txt)

and the file keeps changing the answers i give to answer="cats" to answer=cats.
i dont know y ther are taking the "" away but thats a big no no XD

**Comment by Undeadking176** [comment]
you need anything else i gave u the right file its just name diffrent on my desktop
